backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('general.urls', namespace='Base')),
    path('admin/', admin.site.urls),
    path('store/', include('marketplace.urls', namespace='MarketPlace')),
    path('carbon/', include('carbonfootprint.urls', namespace='Carbon')),
    path('blogs/', include('blogs.urls', namespace='blogs'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/blogs/urls.py
from django.urls import path
from .views import *


app_name = 'blogs'
urlpatterns = [
    path('',Home,name='Home'),
    path('create-blog/',CreateBlog,name='create-Blog'),
    path('blogs/<str:search>',BlogDisplay,name='BlogDisplay'),
    path('user-blogs/',UserBlogs,name='User-Blogs'),
    path('delete-post/<str:id>',DeletePost,name='DeletePost'),
    path('learn/',Learn,name="Learn")
]

backend/general/urls.py
from django.urls import path
from .views import *

app_name = 'Base'

urlpatterns = [
    path('',Home,name="Home"),
    path('login',Login,name="Login"),
    path('logout',Logout,name="Logout"),
    path('faq',FAQ,name="FAQ"),
    path('about',About,name="About"),
    path('profile',Profile,name="Profile")
]

backend/blogs/models.py
from django.db import models
from general.models import UserDetails
from django.utils import timezone

# Create your models here.
#################################################
# BLOGS MODELS
#################################################
class Blogs(models.Model):
    Author = models.ForeignKey(UserDetails,on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=255,blank=False)
    content = models.TextField()
    created = models.DateTimeField(default=timezone.now())
    views  =  models.CharField(max_length=100,blank=True)
    pay   =   models.CharField(max_length=5,blank=True)    
    class Meta:
        verbose_name = 'Blogs'
        verbose_name_plural=verbose_name

backend/blogs/views.py
from django.shortcuts import render, redirect
from blogs.models import Blogs
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.forms.models import model_to_dict

# Create your views here.

# assigning User as our User model i.e. as User_details
User = get_user_model()

@login_required(login_url="Base:Login")
def Home(request):
    Blogs_obj = Blogs.objects.filter(Author = request.user)
    blogs = []
    for i in Blogs_obj:
        blogs.append(model_to_dict(i))
    if (len(blogs) == 0):
        UserBlogs = False
    else:
        UserBlogs = True
    context = {
        "UserBlogs":UserBlogs,
        "blogs":blogs
    }
    return render(request,'blogs/home.html',context = context)

@login_required(login_url="Base:Login")
def CreateBlog(request):
    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        Author = request.user
        new_blog = Blogs.objects.create(Author = Author, title = title, content = content)
        new_blog.save()
        return redirect('blogs:Home')
    return render(request,'blogs/create_blog.html')

def BlogDisplay(request,search):
    search = search.split('-')
    search1 = ''
    for i in search:    search1 = search1+' '+i
    print("SEARCH1:",search1)
    result = Blogs.objects.filter(title = search1[1:]).first()
    if result:
        context = {
            "title":result.title,
            "content":result.content.split('\n'),
        }
    else:
        return redirect('blogs:home')
    return render(request,'blogs/blog_display.html',context)

@login_required(login_url="Base:Login")
def UserBlogs(request):
    if request.method == 'GET':
        user = request.user
        user_blogs = Blogs.objects.filter(Author=user)
        blogs = {}
        count = 0
        for blog in user_blogs:
            blogs[count] = model_to_dict(user_blogs[count])
            count = count + 1
        # print(blogs)
        blogging = {}
        blogging["blogs"] = dict(blogs)
        return render(request,'blogs/user_blogs.html',blogging)
    elif request.method == 'POST':
        search = request.POST['search-title']
        return BlogDisplay(request,search)

@login_required(login_url="Base:Login")
def DeletePost(request,id):
    post = Blogs.objects.get(id = id).delete()
    return redirect('blogs:home')

def Learn(request):
    return render(request,"blogs/learn.html")

backend/frontend/templates/blogs/blog_display.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blogs</title>
</head>
<style>
    * {
        margin:0;
        padding:0;
        box-sizing: border-box;
    }
    .blog-wrapper {
        display: flex;
        flex-direction: column;
        width: calc(100% - 30px);
        min-height: calc(100vh - 200px);
        margin:15px;
        flex-wrap: wrap;
    }
    .blog-title {
        display: flex;
        align-items: center;
        justify-content: center;

        width: 100vw;

        font-size: 30px;
        font-weight: 400;
    }
    .blog-content {
        font-size: 17px;
    }
    .related-searches {
        display:flex;
        justify-content: flex-start;
        align-items: flex-start;
        flex-direction: column;
    }
    a {
        padding:5px 15px;
    }
    ::-webkit-scrollbar {
        width:0px;
    }
    .author {
        display: flex;
        
        font-size: 30px;
        font-weight: 500;
    }
    .blog-content {
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        flex-wrap: wrap;

        margin-top: 10px;
        margin-bottom: 10px;

        font-size: 18px;
    }
</style>
{% include 'components/navbar.html' %}
<body>
<div class="main-wrapper">
    <div class="blog-wrapper">
        <div class="blog-title">{{ title }}</div>
        <!-- <div class="author">Author:{{ author }}</div> -->
        {% comment %} <div class="posted-at">Date:{{ posted-at }}</div> {% endcomment %}
        <div class="blog-content">
            {% comment %} Blog-content
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deserunt eaque, quas perferendis eum
            necessitatibus tenetur repellat facilis excepturi obcaecati ut ad enim sit consequatur ratione dolore
            consequuntur non nulla, cum magnam? Reiciendis sequi distinctio ducimus et, quis consectetur dolore quae at
            veritatis nemo soluta id iusto, quidem perferendis eos nisi asperiores sapiente illum officia sint. {% endcomment %}
            {% for i in content %}
            <p>{{i}}</p>
            {% endfor %}
        </div>
    </div>
    {% comment %} <div class="related-searches">
        <a href="#">Search1</a> <br>
        <a href="#">Search2</a> <br>
        <a href="#">Search3</a> <br>
        <a href="#">Search4</a> <br>
        <a href="#">Search5</a> <br>
        <a href="#">Search6</a> <br>
        <a href="#">Search7</a> <br>
        <a href="#">Search8</a> <br>
        <a href="#">Search9</a> <br>
    </div> {% endcomment %}
</div>
    {% include 'components/footer.html' %}
</body>

</html>

backend/frontend/templates/blogs/create_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Blog</title>
    <style>
        * {
            margin:0;
            padding:0;
            box-sizing:border-box;
        }
        body {
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .mainWrapper{
            overflow-x: hidden;
        }
        .blog-wrapper {
            display:flex;
            flex-direction: column;
            flex-wrap: nowrap;
            width: 100%;
            min-width: 280px;
            margin: 10px;
            border-radius: 5px;
            border: 2px solid black;
        }
        .heading {
            display: flex;
            justify-content: flex-start;
            font-size: 26px;
            margin: auto;
            margin-left:10px;
            margin-bottom: 10px;
        }
        label {
            font-size: 20px;
        }
        .blog-field {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            justify-content: center;
            margin:10px;
        }

        input {
            resize:none;
            width:calc(100% - 10px);
            min-height: 50px;
            padding: 0 10px;
        }
        textarea {
            resize:none;
            width:calc(100% - 10px);
            height: 340px;
            padding: 10px 10px;
        }
        .form-submit {
            display: flex;
            background-color: rgb(9, 155, 9);
            color:white;
            align-items: center;
            justify-content: center;
            border-radius: 5px;
            margin:10px;
            width: 100px;
            height: 40px;
            font-size: 17px;
            border:none;
        }
        .form-submit:hover {
            background-color: rgb(7, 179, 7);
        }
    </style>
</head>
<body>
    <div class="mainWrapper">
    {% include 'components/navbar.html' %}
    <div class="blog-wrapper">
        <form method="POST" action="" class="blog-form">
            {% csrf_token %}
            <div class="heading">
                New Post
            </div>
            <div class="blog-field title">
                <label for="title">Post Title:</label>
                <input type="text" name="title" placeholder="Title of your Post">
            </div>
            <div class="blog-field content">
                <label for="content">Post content:</label>
                <textarea name="content" placeholder="content of your post"></textarea>
            </div>
            <button type="submit" class="form-submit"> Create </button>
        </form>
    </div>
    {% include 'components/footer.html' %}
    
</div>
</body>
</html>

backend/frontend/templates/blogs/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rapyd Blogs</title>
    <style>
        ::-webkit-scrollbar {
            width: 0;
        }
        * {
            margin:0;
            padding:0;
            box-sizing:border-box;
        }
        .mainContainerNoBlogs {
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;

            width: 100vw;
            height: calc(100vh - 200px);

            font-size: 28px;
        }
        .createBlog {
            display: flex;
            align-items: center;
            justify-content: center;

            width: 150px;
            height: 50px;

            border-radius: 10px;
            text-decoration: none;
            cursor: pointer;
            font-size: 20px;

            background-color: #00ec00;
            color: black;
        }

        .mainWrapper {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        /* For User Blogs existing */
        .mainContainer {
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;

            width: 100vw;
        }
        .blogMenu {
            display: flex;
            align-items: center;
            justify-content: space-between;
            flex-direction: row;

            width: calc(100vw - 60px);
            min-width: 300px;

            margin-bottom: 10px;
        }
        .userName {
            display: flex;
            align-items: center;
            justify-content: center;

            width: 150px;
            height: 60px;

            font-size: 30px;
            font-weight: 400;
            color: black;
        }
        .blogsContainer {
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;

            width: calc(100vw - 60px);
            min-width: 300px;
        }
        .blog {
            display: flex;
            align-items: center;
            justify-content: center;
            flex-wrap: wrap;
            flex-direction: column;

            max-width: 700px;
            width: 60vw;
            min-width: 300px;

            border: 1px solid black;
            border-radius: 10px;
            margin: 10px;
            text-decoration: none;
            color: black;
        }
        .blog:hover {
            transform: translateY(-5px);
        }
        .blogTitle {
            display: flex;
            align-items: center;
            justify-content: flex-start;
            flex-wrap: wrap;

            width: 100%; 
            min-height: 30px;  

            font-size: 28px;
            margin: 10px;
        }
        .blog > .created {
            display: flex;
            align-items: center;
            justify-content: flex-end;

            width: 100%;

            font-size: 16px;
            font-weight: 300;
            padding: 15px;
        }
    </style>
</head>
<body>
    {% include 'components/navbar.html' %}
    <div class="mainWrapper">
        
    {% if UserBlogs %}
    <div class="mainContainer">
        <div class="blogMenu">
        <div class="userName">{{request.user.username}}</div>
        <a href="{% url 'blogs:create-Blog' %}" class="createBlog"> Create Blog</a>
        </div>
        <div class="blogsContainer">
            {% for blog in blogs %}
            <a href="{% url 'blogs:BlogDisplay' search=blog.title %}" class="blog">
                <div class="blogTitle"> {{blog.title}} </div>
                <div class="created"> {{blog.created}}</div>
            </a>
            {% endfor %}
        </div>
    </div>
    {% else %}
    <div class="mainContainerNoBlogs">
        You have no Blogs.<br>
        <a href="#" class="createBlog"> Create Blog</a>
    </div>
    {% endif %}
    
    </div>
    {% include 'components/footer.html' %}

</body>
</html>

backend/frontend/templates/blogs/learn.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> EcoIN | Learn </title>
    <style>
        * {
            margin:0;
            padding:0;
            box-sizing:border-box;
        }
        .development {
            display: flex;
            justify-content:center;
            align-items:center;
            margin:auto;
            margin-top:150px;
            margin-bottom:150px;
        }
        .box-wrapper {
            
            display: flex;
            align-items:center;
            justify-content:center;
            min-width:280px;
            height:150px;
            font-size:20px;
            border-radius:10px;
            border: 1px solid black;
            flex-direction:column;
        }
        .content-tag {
            display: flex;
            height: 95vh;
            width:100%;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    {% include 'components/navbar.html' %}

    {% comment %} {% endcomment %}
    <div class="content-tag">
        <div class="development">
            <div class="box-wrapper">
                Under Development   <br>
                <a href="{% url 'Base:Home' %}">Go Back</a>
            </div>
        </div> 
    </div>
    {% include 'components/footer.html' %}

</body>
</html>

backend/frontend/templates/blogs/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
  />
<link rel="stylesheet" href="{% static 'CSS/userProfile.css' %}">
<div class="wrapper">
    <nav>
      <input type="checkbox" id="show-search" />
      <input type="checkbox" id="show-menu" />
      <label for="show-menu" class="menu-icon"
        ><i class="fas fa-bars"></i
      ></label>
      <div class="content">
        <div class="logo"><a href="{% url 'Base:Home' %}">EcoIN</a></div>
        <ul class="links">
          <li><a href="{% url 'blogs:home' %}">Home</a></li>
          <li><a href="{% url 'blogs:home' %}">About</a></li>
          <li><a href="{% url 'Base:FAQ' %}">FAQ</a></li>
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'UserProfile' request.user.username %}" class="desktop-link">{{request.user.username}}</a>
            <input type="checkbox" id="show-features" />
            <label for="show-features">{{request.user.username}}</label>
            <ul>
                <li><a href="#">Profile</a></li>
                <li><a href="{% url 'Base:Logout' %}">Logout</a></li>
                <li><a href="{% url 'blogs:User-Blogs' %}">Your Blogs</a></li>
            </ul>
        </li>
        <li><a href="{% url 'blogs:create-post' %}">Create Blogs</a></li>
          {% else %} 
          <li><a href="{% url 'Base:Login' %}">Login/Signup</a></li>
          {% endif %}
          </ul>
        </div>
        <label for="show-search" class="search-icon"
          ><i class="fas fa-search"></i
        ></label>
        <form action="" method="post" class="search-box">
            {% csrf_token %}
          <input
            type="text"
            placeholder="Type Something to Search..."
            name = "search-title"
          />
          <button type="submit" class="go-icon">
            <i class="fas fa-long-arrow-alt-right"></i>
          </button>
        </form>
      </nav>
</div>
</html>