backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('general.urls', namespace='Base')),
    path('admin/', admin.site.urls),
    path('store/', include('marketplace.urls', namespace='MarketPlace')),
    path('carbon/', include('carbonfootprint.urls', namespace='Carbon')),
    path('blogs/', include('blogs.urls', namespace='blogs'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/blogs/urls.py
from django.urls import path
from .views import *


app_name = 'blogs'
urlpatterns = [
    path('',Home,name='Home'),
    path('create-blog/',CreateBlog,name='create-Blog'),
    path('blogs/<str:search>',BlogDisplay,name='BlogDisplay'),
    path('user-blogs/',UserBlogs,name='User-Blogs'),
    path('delete-post/<str:id>',DeletePost,name='DeletePost'),
    path('learn/',Learn,name="Learn")
]

backend/carbonfootprint/urls.py
from django.urls import path
from .views import *

app_name = "Carbon"

urlpatterns = [
    path('',Home,name="Home"),
    path('individual-calculator',IndividualCalculator,name="IndividualCalculator"),
    path('business-calculator',BusinessCalculator,name="BusinessCalculator"),
]

backend/carbonfootprint/models.py
from django.db import models

# Create your models here.

backend/carbonfootprint/views.py
from django.shortcuts import render, HttpResponse
from backend.settings import GPT_KEY
import requests
# Create your views here.
def Home(request):
    return render(request,'carbonfootprint/perspective.html')

def IndividualCalculator(request):
    if request.method == "POST":
        print(request.POST.items())
        emission = 0
        current = float(request.POST['electricity'])   # In units = KWH
        gas = float(request.POST['gas'])   # In grams
        vehicle = request.POST['vehicle']   # Car , Bus
        milage = float(request.POST['mileage'])
        distance =float( request.POST['distance'])
        emissions_factor = 0

        if (vehicle == "Car"):
            car_fuel = request.POST['fuel']     # Data is shared in the group
            if car_fuel == 'gasoline':
                emissions_factor = 2.31  # in kg CO2 per liter
            elif car_fuel == 'diesel':
                emissions_factor = 2.68  # in kg CO2 per liter
        elif (vehicle == "Bus"):
            car_fuel = request.POST['fuel']     # Data is shared in the group
            emissions_factor = 0.68  # in kg CO2 per km

        # Fuel

        if vehicle == 'car':
            emission = (distance / milage) * emissions_factor
        elif vehicle == 'bus':
            emission = distance * emissions_factor
        # Electricity
        emissions_factor = 0.93
        emission = emission + current*emissions_factor
        
        #LPG
        emissions_factor = 2.983
        emission = emission + emissions_factor*gas

        # GPT WORK
        prompt = "Emission :" + str(emission) + ". Suggest ways to reduce it"
        target_url = "https://api.openai.com/v1/completions"
        header = {
        "Authorization" : "Bearer " + GPT_KEY 
        # For Organizations
        # "<Organization_name>" : "<KEY>"
        }

        # To get the available models list.
        # response = requests.request(method="POST",url=target_url,headers=header)

        header["Content-Type"] = "application/json"

        body = {
        "model": "gpt-3.5-turbo",
        "messages": [{"role": "user", "content": "Hello!"}]
        }

    
        response = requests.request(method="POST",url=target_url,headers=header,data = body)
        result = response.json()

        print("==============================")
        print(f"The output is:\n{result}")


        context = {
            "electricity": current,
            "gas":gas,
            "ac":float(request.POST['ac']),
            "vehicle":vehicle,
            "mileage":milage,
            "distance":distance,
            "prompt":True
        }
        context['emission'] = round(emission,3)
        return render(request,"carbonfootprint/individual.html", context = context)
    context = {
            "electricity": 0,
            "gas":0 ,
            "ac":0,
            "vehicle":"petrol",
            "mileage":0,
            "distance":0
    }
    return render(request,"carbonfootprint/individual.html",context=context)

def BusinessCalculator(request):
    return render(request,"carbonfootprint/business.html")

backend/frontend/templates/carbonfootprint/business.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static '/carbonfoot/business.css' %}">
    <link rel="stylesheet" href="/EcoIN/frontend/static/carbonfoot/business.css">
    <title>Document</title>
</head>
<body>
    {% include 'components/navbar.html' %}

    <div class="container">
        <h1>Carbon FootPrint Calculator</h1>
       <form action="" class="box">
            <label for="bill">Electricity Consumption : </label>
            <input type="text" id="bill" name="bill" placeholder="Enter Amount of Units Consumed">
            <label for="car">Car Type (Used for Transporting Employs) : </label>
            <select name="car" id="car">
                <option value="petrol">Petrol</option>
                <option value="diesel">Diesel</option>
                <option value="cng">CNG</option>
                <option value="ev">Ev and Hybrids</option>
            </select>
            <label for="mileage">MileAge : </label>
            <input type="text" name="'mileage" id="mileage" placeholder="Enter MileAge of your car">
            <label for="distance">Distance Travelled : </label>
            <input type="text" id="distance" name="distance" placeholder="Enter Distance Travelled">
            <label for="ac">Air Condition Usage : </label>
            <input type="text" id="ac" name="ac" placeholder="Enter Air Condition Consumption">
            <button type="submit">Calculate</button>
       </form>
    </div>

    {% include 'components/footer.html' %}
</body>
</html>

backend/frontend/templates/carbonfootprint/individual.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static '/carbonfoot/individual.css' %}">
    <link rel="stylesheet" href="/EcoIN/frontend/static/carbonfoot/individual.css">
    <title>Document</title>
</head>
<body>
    {% include 'components/navbar.html' %}

    <div class="container">
        {% if emission %}
        <h1> You carbon emission is: {{emission}} </h1>
        {% else%}
        <h1>Carbon FootPrint Calculator</h1>
        {% endif %}
       <form action="" method="POST" class="box">
            {% csrf_token %}
            <label for="bill">Electricity Consumption : </label>
            <input type="text" id="bill" name="electricity" placeholder="Enter Amount of Units Consumed" value={{electricity}}>
            <label for="vehicle">Car Type : </label>
            <select name="vehicle" id="car" value={{vehicle}}>
                <option value="petrol">Petrol</option>
                <option value="diesel">Diesel</option>
                {% comment %} <option value="cng">CNG</option>
                <option value="ev">Ev and Hybrids</option> {% endcomment %}
            </select>
            <label for="mileage">MileAge : </label>
            <input type="text" name="mileage" id="mileage" placeholder="Enter MileAge of your car"  value={{mileage}}>
            <label for="distance">Distance Travelled : </label>
            <input type="text" id="distance" name="distance" value={{distance}} placeholder="Enter Distance Travelled">
            <label for="gas">LPG Consumption (in grams) : </label>
            <input type="text" id="gas" name="gas" value={{gas}} placeholder="Enter LPG Consumption">
            <label for="ac">Air Conditioner Usage : </label>
            <input type="text" id="ac" name="ac" value={{ac}} placeholder="Enter Air Condition Consumption">
            <button type="submit">Calculate</button>
       </form>
       {% if prompt %}
       <div class="promptBox">
        <div class="tips">
            <div class="heading">Here are some tips you can improve:</div>
            Try to reduce the usage of current by spending more time outside the home.
            <br>
            Reduce the time of your AC usage
            <br>
            Prefer cab sharing
            
        </div>
       </div>
       {% else %}
       {% endif %}
    </div>

    {% include 'components/footer.html' %}
    <script>
        document.querySelector(".box").onSubmit = (e) => {
            e.preventDefault();
        }
       </script>
</body>
</html>

backend/frontend/templates/carbonfootprint/perspective.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static '/carbonfoot/perspective.css' %}">
    <link rel="stylesheet" href="/EcoIN/frontend/static/carbonfoot/perspective.css">
    <title>Document</title>
</head>
<body>
    {% include 'components/navbar.html' %}

    <div class="container">
        <a href="{% url 'Carbon:IndividualCalculator'%}">
        <div class="person box">
            <h4>Individual</h4>
                <i class="fa fa-user" style="font-size:30px;color:white;" aria-hidden="true"></i>
        </div>
        </a>
        <a href="{% url 'Carbon:BusinessCalculator'%}">
        <div class="business box">
            <h4>Business</h4>
                <i class="fa fa-building" style="font-size:30px;color:white;" aria-hidden="true"></i>
        </div>
        </a>
    </div>

    {% include 'components/footer.html' %}
</body>
</html>