backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('general.urls', namespace='Base')),
    path('admin/', admin.site.urls),
    path('store/', include('marketplace.urls', namespace='MarketPlace')),
    path('carbon/', include('carbonfootprint.urls', namespace='Carbon')),
    path('blogs/', include('blogs.urls', namespace='blogs'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/blogs/urls.py
from django.urls import path
from .views import *


app_name = 'blogs'
urlpatterns = [
    path('',Home,name='Home'),
    path('create-blog/',CreateBlog,name='create-Blog'),
    path('blogs/<str:search>',BlogDisplay,name='BlogDisplay'),
    path('user-blogs/',UserBlogs,name='User-Blogs'),
    path('delete-post/<str:id>',DeletePost,name='DeletePost'),
    path('learn/',Learn,name="Learn")
]

backend/general/urls.py
from django.urls import path
from .views import *

app_name = 'Base'

urlpatterns = [
    path('',Home,name="Home"),
    path('login',Login,name="Login"),
    path('logout',Logout,name="Logout"),
    path('faq',FAQ,name="FAQ"),
    path('about',About,name="About"),
    path('profile',Profile,name="Profile")
]

backend/marketplace/urls.py
from django.urls import path
from .views import *

app_name = 'MarketPlace'

urlpatterns = [
     path('',Home,name="Home"),
     path('cart',ProductsCart,name="Cart"),
     path('wishlist',ProductsWishlist,name="Wishlist"),
     path('product/<str:id>',ProductPage,name="ProductPage"),
     path('payment',PaymentDirection,name="Payment")
]

backend/marketplace/models.py
from django.db import models
from general.models import UserDetails
from django.utils import timezone

# Create your models here.
class Product(models.Model):
    Name    =   models.CharField(max_length=150)
    Desc    =   models.TextField(default="")
    Img     =   models.ImageField()
    Company =   models.CharField(max_length=150)
    Stock   =   models.CharField(max_length=10)
    Created =   models.DateTimeField(timezone.now)
    Price   =   models.CharField(max_length=10)
    Type    =   models.CharField(max_length=10,default="New")   # Recycled or Fresh Arrival
    def __str__(self):
        return self.Name
    class Meta:
        verbose_name = "Product"
        verbose_name_plural=verbose_name

class Cart(models.Model):
    User    =   models.ForeignKey(UserDetails,on_delete=models.DO_NOTHING)
    Prod_Id =   models.ManyToManyField(Product)
    Qty     =   models.CharField(max_length=10)
    class Meta:
        verbose_name = "Cart"
        verbose_name_plural=verbose_name

class Wishlist(models.Model):
    User    =   models.ForeignKey(UserDetails,on_delete=models.DO_NOTHING)
    Prod_Id =   models.ManyToManyField(Product)
    class Meta:
        verbose_name = "WishList"
        verbose_name_plural=verbose_name

backend/marketplace/views.py
from django.shortcuts import render,redirect, HttpResponse
from .models import *
from django.forms.models import model_to_dict
from django.contrib.auth.decorators import login_required
from .rapyd_apis import make_request

# Create your views here.
def Home(request):
    products_obj = Product.objects.all()
    products = []
    for i in products_obj:
        products.append(model_to_dict(i))

    context = { "items" : products }
    return render(request,'marketplace/productcard.html',context=context)

def ProductsCart(request):
    return render(request,'marketplace/productcard.html')

def ProductsWishlist(request):
    return render(request,'marketplace/productcard.html')

def ProductPage(request,id):
    products_obj = Product.objects.filter(id = id).first()
    product = model_to_dict(products_obj)
    context = product
    print(context)
    return render(request,"marketplace/SingleCard.html",context=context)

@login_required(login_url='Base:Login')
def PaymentDirection(request):
    wallet_body = {
        "amount": 50,
        "currency": "USD",
        "country":"US",
        "complete_payment_url":"Eco_Sotre:Home",
        #Change this github link at the time of production. to the website link
        #Rapyd do not allow urls of local host. Thats why we kept github here
        "complete_checkout_url":"https://www.github.com/anirudh3167",
        "error_payment_url":"store:Failed"
    }
    response = make_request(method='post',path='/v1/checkout',body=wallet_body)
    #print(response)
    hosted_url = response['data']['redirect_url']
    #print("REDIRECT_URL:",hosted_url)
    return redirect(hosted_url)

backend/frontend/templates/marketplace/SingleCard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static '/marketplace/singleCard.css' %}">
    <!-- <link rel="stylesheet" href="/EcoIN/frontend/static/marketplace/singleCard.css"> -->
    <title>Document</title>
</head>
<body>
    
    {% include 'components/navbar.html' %}

    <div class="main-cont">
        
        <img src="{% static 'images/' %}{{ Img }}" alt="Product Image" height="150px">

        <div class="info-cont">
            <h2>{{Name}}</h2>
            <h6>{{Company}}</h6>
            <h4>&#8377; <span>{{Price}}</span></h4>
            <p>{{Desc}}</p>
            <div class="btn-cont">
                <div>
                    <button class="toCart">Add to cart</button>
                    <button class="fav"><i onclick="myFunction(this)" class="fa fa-heart-o fa-heart"></i></button>
                </div>
                <div>
                    <a href="{% url 'MarketPlace:Payment' %}">
                        <button class="buyNow-btn" style="min-width:150px;width:10vw;max-width:400px;">Buy Now</button>
                    </a>
                </div>
            </div>
        </div>       

    </div>
    {% include 'components/footer.html' %}

    <script>
        var productData = {
            name: "Product Name",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis diam eu mi dictum tempus. Aenean posuere eu urna eget condimentum.",
            image: "product-image.jpg",
            wishlisted: 0
        };

        var cards = document.getElementsByClassName("info-cont")
        for (let i = 0; i < cards.length; i++) {

            let wishclickcount = 0;
            var favButton = cards[i].querySelector(".fav");

            function myFunction(x) {
                wishclickcount += 1;
                productData.wishlisted = wishclickcount%2;
                x.classList.toggle("fa-heart-o");
            }
        }
    </script>
</body>
</html>

backend/frontend/templates/marketplace/navStore.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'marketplace/navbar.css' %}">
    <style>
      a {
        text-decoration:none;
        padding: 8px 13px;
        font-size: 18px;
        font-weight: 500;
        padding: 9px 17px;
        border-radius: 5px;
        transition: all 0.3s ease;
      }
    </style>
</head>
<body>
  <div class="wrapper">
    <nav>
    <input type="checkbox" id="show-search" />
    <input type="checkbox" id="show-menu" />
    <label for="show-menu" class="menu-icon"
        ><i class="fas fa-bars"></i
    ></label>
    <div class="content">
        <ul class="links">
        <li><a href="{% url 'Base:Home' %}">Home</a></li>
        <li><a href="{% url 'Base:About' %}">About</a></li>
        <li>
            <a href="{% url 'Carbon:Home' %}" class="desktop-link">Carbon Footprint </a>
        </li>
        <li>
            <a href="{% url 'MarketPlace:Home' %}" class="desktop-link">Eco Store</a>
            <input type="checkbox" id="show-store" />
            <label for="show-store">Eco Store</label>
            <ul>
            <li><a href="{% url 'MarketPlace:Home' %}"> Buy New </a></li>
            <li><a href="#"> Reused </a></li>
            </ul>
        </li>
        <li>
            <a href="#" class="desktop-link">Educate</a>
            <input type="checkbox" id="show-edu" />
            <label for="show-edu">Educate</label>
            <ul>
            <li><a href="#"> Blogs </a></li>
            <li><a href="#"> Learn </a></li>
            </ul>
        </li>
        <li><a href="{% url 'Base:FAQ' %}">FAQ</a></li>
        {% if user.is_authenticated %}
        <li><a href="#">Profile</a></li>
        <li><a href="{% url 'Base:Logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'Base:Login' %}">Login/Signup</a></li>
        {% endif %}
        
        </ul>
        <div class="logo"><a href="{% url 'Base:Home' %}">Eco<font color="#00ffd9">IN</font></a></div>
    </div>
    </nav>
</div>
<div style="height: 70px;"><img src="{% static 'images/overscroll.png' %}" width="100%" height="100%"></div>
</body>
</html>

backend/frontend/templates/marketplace/productcard.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Product Card</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static '/marketplace/productCard.css' %}">
</head>
<body>
<div class="mainWrapper">
    {% include 'components/navbar.html' %}
    <div class="mainContainer">
    {% for item in items %}
    {% comment %} Product id needs to added as hidden attribute {% endcomment %}
        <div class="card">
            <div class="cardWrapper" onclick="showProduct({{item.id}})">
            <img src="{% static 'images/' %}{{item.Img}}" alt="Product Image" height="150px">
            <h2> {{item.Name }}</h2>
            <h6>{{ item.Company }}</h6>
            <h4>&#8377; <span>{{ item.Price }}</span></h4>
            <p>{{ item.Desc }}</p>
            </div>
            <button class="toCart" onclick="addCart({{item.id}})">Add to cart</button>
            <button style="float: right;" class="fav"><i onclick="myFunction(this,{{item.id}})" class="fa fa-heart-o fa-heart"></i></button>
        </div>
    {% endfor %}
    </div>
    {% include 'components/footer.html' %}
</div>
    <script>
        function showProduct(id) {
            window.location = "http://localhost:8000/store/product/" + id;
        }
        var productData = {
            name: "Product Name",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla quis diam eu mi dictum tempus. Aenean posuere eu urna eget condimentum.",
            image: "product-image.jpg",
            wishlisted: 0
        };

        
        var cards = document.getElementsByClassName("card")
        for (let i = 0; i < cards.length; i++) {

            let wishclickcount = 0;
            var favButton = cards[i].querySelector(".fav");

            async function myFunction(x,id) {
                wishclickcount += 1;
                productData.wishlisted = wishclickcount%2;
                x.classList.toggle("fa-heart-o");
            }
        }
    </script>
</body>
</html>

backend/frontend/templates/marketplace/reused.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> EcoIN | Store </title>
    <style>
        * {
            margin:0;
            padding:0;
            box-sizing:border-box;
        }
        .development {
            display: flex;
            justify-content:center;
            align-items:center;
            margin:auto;
            margin-top:150px;
            margin-bottom:150px;
        }
        .box-wrapper {
            
            display: flex;
            align-items:center;
            justify-content:center;
            min-width:280px;
            height:150px;
            font-size:20px;
            border-radius:10px;
            border: 1px solid black;
            flex-direction:column;
        }
        .content-tag {
            display: flex;
            height: 95vh;
            width:100%;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>
<body>
    {% include 'components/navbar.html' %}

    {% comment %} {% endcomment %}
    <div class="content-tag">
        <div class="development">
            <div class="box-wrapper">
                Under Development   <br>
                <a href="{% url 'Base:Home' %}">Go Back</a>
            </div>
        </div> 
    </div>
    {% include 'components/footer.html' %}

</body>
</html>