backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('general.urls', namespace='Base')),
    path('admin/', admin.site.urls),
    path('store/', include('marketplace.urls', namespace='MarketPlace')),
    path('carbon/', include('carbonfootprint.urls', namespace='Carbon')),
    path('blogs/', include('blogs.urls', namespace='blogs'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/blogs/urls.py
from django.urls import path
from .views import *


app_name = 'blogs'
urlpatterns = [
    path('',Home,name='Home'),
    path('create-blog/',CreateBlog,name='create-Blog'),
    path('blogs/<str:search>',BlogDisplay,name='BlogDisplay'),
    path('user-blogs/',UserBlogs,name='User-Blogs'),
    path('delete-post/<str:id>',DeletePost,name='DeletePost'),
    path('learn/',Learn,name="Learn")
]

backend/general/urls.py
from django.urls import path
from .views import *

app_name = 'Base'

urlpatterns = [
    path('',Home,name="Home"),
    path('login',Login,name="Login"),
    path('logout',Logout,name="Logout"),
    path('faq',FAQ,name="FAQ"),
    path('about',About,name="About"),
    path('profile',Profile,name="Profile")
]

backend/frontend/templates/components/footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/footercss.css' %}">
</head>
<body>
    <div class="container" style="padding:0;">
        <footer class="footer">
            <div class="waves">
                <div class="wave" id="wave1"></div>
                <div class="wave" id="wave2"></div>
                <div class="wave" id="wave3"></div>
                <div class="wave" id="wave4"></div>
            </div>
            <ul class="social-icon">
                <li class="social-icon__item"><a class="social-icon__link" href="#">
                    <ion-icon name="logo-facebook"></ion-icon>
                </a></li>
                <li class="social-icon__item"><a class="social-icon__link" href="#">
                    <ion-icon name="logo-twitter"></ion-icon>
                </a></li>
                <li class="social-icon__item"><a class="social-icon__link" href="#">
                    <ion-icon name="logo-linkedin"></ion-icon>
                </a></li>
                <li class="social-icon__item"><a class="social-icon__link" href="#">
                    <ion-icon name="logo-instagram"></ion-icon>
                </a></li>
            </ul>
            <ul class="menu">
                <li class="menu__item"><a class="menu__link" href="{% url 'Base:Home' %}">Home</a></li>
                <li class="menu__item"><a class="menu__link" href="#">Carbon Footprint</a></li>
                <li class="menu__item"><a class="menu__link" href="{% url 'MarketPlace:Home' %}">Eco Store</a></li>
                <li class="menu__item"><a class="menu__link" href="#">Educate</a></li>
                <li class="menu__item"><a class="menu__link" href="#">Blog</a></li>
        
            </ul>
            <p>&copy;EcoIN | CodeGeeks</p>
            </footer>
            <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    </div>
</body>
</html>

backend/frontend/templates/components/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/navCss.css' %}">
    <style>
      a {
        text-decoration:none;
        padding: 8px 13px;
        font-size: 18px;
        font-weight: 500;
        padding: 9px 17px;
        border-radius: 5px;
        transition: all 0.3s ease;
        font-family: sans-serif;
      }
    </style>
</head>
<body>
  <div class="wrapper">
    <nav>
    <input type="checkbox" id="show-search" />
    <input type="checkbox" id="show-menu" />
    <label for="show-menu" class="menu-icon"
        ><i class="fas fa-bars"></i
    ></label>
    <div class="content">
        <ul class="links">
        <li><a href="{% url 'Base:Home' %}">Home</a></li>
        <li><a href="{% url 'Base:About' %}">About</a></li>
        <li>
            <a href="{% url 'Carbon:Home' %}" class="desktop-link">Carbon Footprint </a>
        </li>
        <li>
            <a href="{% url 'MarketPlace:Home' %}" class="desktop-link">Eco Store</a>
            <input type="checkbox" id="show-store" />
            <label for="show-store">Eco Store</label>
            <ul>
            <li><a href="{% url 'MarketPlace:Home' %}"> Buy New </a></li>
            <li><a href="#"> Reused </a></li>
            </ul>
        </li>
        <li>
            <a href="#" class="desktop-link">Educate</a>
            <input type="checkbox" id="show-edu" />
            <label for="show-edu">Educate</label>
            <ul>
            <li><a href="{% url 'blogs:Home' %}"> Blogs </a></li>
            <li><a href="{% url 'blogs:Learn' %}"> Learn </a></li>
            </ul>
        </li>
        <li><a href="{% url 'Base:FAQ' %}">FAQ</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'Base:Profile' %}">Profile</a></li>
        <li><a href="{% url 'Base:Logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'Base:Login' %}">Login/Signup</a></li>
        {% endif %}
        
        </ul>
        <div class="logo"><a href="{% url 'Base:Home' %}">Eco<font color="#00ffd9">IN</font></a></div>
    </div>
    </nav>
</div>
<div style="height: 70px;"><img src="{% static 'images/overscroll.png' %}" width="100%" height="100%"></div>
</body>
</html>